// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQUJZ6f6Z60Em1Z67JkNP_oXTbjnKco9w',
    appId: '1:336523389202:web:37228a79c3bb619e4a2bcb',
    messagingSenderId: '336523389202',
    projectId: 'linge-81467',
    authDomain: 'linge-81467.firebaseapp.com',
    storageBucket: 'linge-81467.firebasestorage.app',
    measurementId: 'G-K7NN1PD5YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC77M5w-Ti8ai_Z6hqqiis_4I4MpX2ZDsU',
    appId: '1:336523389202:android:b27db4a1cef4d6384a2bcb',
    messagingSenderId: '336523389202',
    projectId: 'linge-81467',
    storageBucket: 'linge-81467.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP9SbRv6R3ysRRQoIYeYyKPyajlqID4kA',
    appId: '1:336523389202:ios:113c7e19a07c1da64a2bcb',
    messagingSenderId: '336523389202',
    projectId: 'linge-81467',
    storageBucket: 'linge-81467.firebasestorage.app',
    iosBundleId: 'com.example.makelinge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP9SbRv6R3ysRRQoIYeYyKPyajlqID4kA',
    appId: '1:336523389202:ios:113c7e19a07c1da64a2bcb',
    messagingSenderId: '336523389202',
    projectId: 'linge-81467',
    storageBucket: 'linge-81467.firebasestorage.app',
    iosBundleId: 'com.example.makelinge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQUJZ6f6Z60Em1Z67JkNP_oXTbjnKco9w',
    appId: '1:336523389202:web:c45b30ea06ad94c24a2bcb',
    messagingSenderId: '336523389202',
    projectId: 'linge-81467',
    authDomain: 'linge-81467.firebaseapp.com',
    storageBucket: 'linge-81467.firebasestorage.app',
    measurementId: 'G-8H4FQFZFSN',
  );
}
